name: jeevan_diabetes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  device_preview: ^1.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_html: ^3.0.0-beta.2
  flutter_snake_navigationbar: ^0.6.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0
  http: ^1.2.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  pod_player: ^0.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/